name: Go
on: [push,pull_request]
jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check test_result code into the Go module directory
      uses: actions/checkout@v1

    - name: Build & Test
      run: make ci
